site_name: Infinity
theme:
  name: material
extra:
  version:
    provider: mike
plugins:
   - swagger-ui-tag:
        background: White
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences