name: docs-gh-pages 

on:
  release:
    types: [published]
  push:
    branches:
    - main
    - dev
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install poetry && poetry config virtualenvs.create false
      - run: cd libs/infinity_emb && poetry install --extras "server" --with mkdocs
      - run: 
          echo "INFINITY_VERSION=$(python -c 'import infinity_emb; print(infinity_emb.__version__)')" >> $GITHUB_ENV
      - run:
          cd docs && \
          python -m mkdocs gh-deploy --force --push --update-aliases latest $INFINITY_VERSION