---
name: Publish to pypi -> libs/infinity_emb

on:
  release:
    types: [published]

env:
  POETRY_VERSION: "1.6.1"
  WORKDIR: "libs/infinity_emb"

env:
  POETRY_VERSION: "1.6.1"

jobs:
  build:
    # Disallow publishing from branches that aren't `master`.
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python + Poetry ${{ env.POETRY_VERSION }}
        uses: "./.github/actions/poetry_setup"
        with:
          python-version: "3.10"
          poetry-version: ${{ env.POETRY_VERSION }}
          working-directory: ${{ inputs.working-directory }}
          cache-key: release

      - name: Build project for distribution
        shell: bash
        run: poetry build
      
      - name: Check Version
        id: check-version
        run: |
          echo version=$(poetry version --short) >> $GITHUB_OUTPUT
          
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ inputs.working-directory }}/dist/
          verbose: true
          print-hash: true